# Shared numeric constants for DPS calculations
EFFECTIVE_LEVEL_BASE = 8
VOID_MELEE_MULTIPLIER = 1.1
VOID_RANGED_ATTACK_MULTIPLIER = 1.1
VOID_RANGED_STRENGTH_MULTIPLIER = 1.125
VOID_MAGIC_MULTIPLIER = 1.45
TWISTED_BOW_MAGIC_CAP = 250
TWISTED_BOW_MAX_ACCURACY = 1.4
TWISTED_BOW_MAX_DAMAGE = 2.5
EQUIPMENT_BONUS_OFFSET = 64
MAX_HIT_DIVISOR = 640
