export const OSRS_LOADING_JOKES = [
  "Why don't NPCs ever get tired? Because they have unlimited run energy!",
  "What do you call a dragon that won't attack? A drag-on!",
  "Why did the player quit fishing? They were tired of being catfished by empty spots!",
  "What's a PKer's favorite type of music? Heavy metal... armor!",
  "Why don't goblins make good comedians? Their jokes are always goblin up the punchline!",
  "What do you call a cow that gives no milk? An udder disappointment... just like my RNG!",
  "Why did the chicken cross Lumbridge? To get to the other side quest!",
  "What's the difference between a noob and a cabbage? The cabbage has better stats!",
  "Why don't fire giants ever get cold? They're always lit!",
  "What do you call a player who only trains combat? A one-trick pony... with 99 Attack!",
  "Why did the player break up with their girlfriend? She said RuneScape was just a game!",
  "What's a wizard's favorite type of spell? A spell-binding one!",
  "Why don't chaos druids make good doctors? They only know how to cast confusion!",
  "What do you call a player with 99 Thieving? A professional pickpocket... I mean, entrepreneur!",
  "Why did the dwarf refuse to mine coal? He said it was beneath him!",
  "What's the best thing about training Agility? The run-ning gags!",
  "Why don't demons ever win at poker? They always fold under pressure!",
  "What do you call a player who only does quests? A quest-ion mark!",
  "Why did the barbarian go to therapy? He had too much rage!",
  "What's a banker's favorite skill? Banking... wait, that's not a skill!",
  "Why don't zombies make good dancers? They're always dead on their feet!",
  "What do you call a player with 1 Defence? A glass cannon... emphasis on glass!",
  "Why did the tree refuse to be cut down? It was rooted in its beliefs!",
  "What's the difference between a pure and a main? About 70 Defence levels!",
  "Why don't rangers ever miss their targets? Because they always bow to pressure!",
  "What do you call a player who AFKs too much? A professional sleeper!",
  "Why did the mage stop casting spells? He ran out of runes... and patience!",
  "What's a PKer's least favorite weather? Fog... it ruins their vision!",
  "Why don't goblins ever win races? They're always goblin behind!",
  "What do you call a player with max stats? Unemployed!",
  "Why did the lobster leave the cooking range? It was getting too heated!",
  "What's the best thing about 99 Woodcutting? You're finally ready to start playing!",
  "Why don't NPCs ever move houses? They're stuck in their dialogue loops!",
  "What do you call a player who only trains Prayer? Holy devoted!",
  "Why did the cow file a police report? It got beefed by a PKer!",
  "What's a merchant's favorite type of profit? Prophet... I mean, profit!",
  "Why don't skeletons ever get scared? They don't have the guts!",
  "What do you call a player who only does Slayer? A monster hunter... literally!",
  "Why did the rock crab change shells? It wanted a new perspective!",
  "What's the difference between a bond and a membership? About $5 and your dignity!",
  "Why don't unicorns exist in OSRS? Because horns are too OP!",
  "What do you call a player with 99 Runecrafting? A masochist!",
  "Why did the spider stop spinning webs? It got caught up in the grind!",
  "What's a flipper's favorite market condition? When prices are all over the place!",
  "Why don't ghosts make good PKers? They can't handle the pressure!",
  "What do you call a player who never banks? A hoarder with commitment issues!",
  "Why did the dragon breathe fire? It was having a heated argument!",
  "What's the best thing about getting hacked? A fresh start... and trust issues!",
  "Why don't NPCs ever get promoted? They're stuck in entry-level positions!",
  "What do you call a player who's been grinding for 20 years? A veteran... or in need of help!",
];
