name: Misc CI

on:
  push:
    branches: [ main, testing-branch ]
    paths:
      - ".pre-commit-config.yaml"
      - "**/*.py"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.md"
      - ".github/workflows/ci-misc.yml"
  pull_request:
    branches: [ main, testing-branch ]
    paths:
      - ".pre-commit-config.yaml"
      - "**/*.py"
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.md"
      - ".github/workflows/ci-misc.yml"
  workflow_dispatch:
    inputs:
      hook:
        description: "Run a specific pre-commit hook id (optional)"
        required: false
        default: ""
  workflow_call:
    inputs:
      hook:
        required: false
        type: string
        default: ""

permissions:
  contents: read

concurrency:
  group: misc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  precommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            precommit-${{ runner.os }}-

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Run pre-commit
        run: |
          if [ -n "${{ inputs.hook || github.event.inputs.hook || '' }}" ]; then
            pre-commit run --all-files ${{ inputs.hook || github.event.inputs.hook }}
          else
            pre-commit run --all-files
          fi
