name: Create Issue from Bug Report

on:
  repository_dispatch:
    types: [bug_report]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload.client_payload || {};
            const title = payload.title || 'Bug report';
            const body = payload.body || '';
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['bug-report']
            });
            console.log(`Created issue: ${issue.html_url}`);
