name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]  # Trigger when backend changes
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]
  workflow_dispatch:  # Allow manual deployment

env:
  AZURE_WEBAPP_NAME: 'scapelab-api-dvawaebtdze3brf0'  # Your full app name
  AZURE_WEBAPP_PACKAGE_PATH: './backend'
  PYTHON_VERSION: '3.12'  # Match your App Service Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Backend to App Service
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        cache-dependency-path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/requirements.txt'

    - name: 'Create and start virtual environment'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        python -m venv venv
        source venv/bin/activate

    - name: 'Install dependencies'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        source venv/bin/activate
        pip install -r requirements.txt

    - name: 'Run tests (optional)'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        source venv/bin/activate
        # Add your test commands here if you have tests
        # python -m pytest tests/ || echo "No tests found"

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure App Service (Staging Slot for PR)'
      if: github.event_name == 'pull_request'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        slot-name: 'staging'

    - name: 'Deploy to Azure App Service (Production)'
      if: github.event_name != 'pull_request'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: 'Test deployed API'
      if: github.event_name != 'pull_request'
      run: |
        echo "Testing API endpoints..."
        sleep 30  # Wait for deployment to complete
        
        # Test root endpoint
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/ || echo "Root endpoint failed"
        
        # Test health/docs endpoint
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/docs || echo "Docs endpoint failed"
        
        # Test bosses endpoint (should return JSON)
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/bosses || echo "Bosses endpoint failed"