name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]  # Only trigger on backend changes
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]  # Only trigger on backend changes
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'ScapeLab-API'  # Your full app name
  AZURE_WEBAPP_PACKAGE_PATH: './backend'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Backend to App Service
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        cache-dependency-path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/requirements.txt'

    - name: 'Create and start virtual environment'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        python -m venv venv
        source venv/bin/activate

    - name: 'Install dependencies'
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        source venv/bin/activate
        pip install -r requirements.txt

    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: 'Test deployed API'
      run: |
        echo "Testing API endpoints..."
        sleep 30
        
        # Test root endpoint
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/ || echo "Root endpoint failed"
        
        # Test health/docs endpoint
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/docs || echo "Docs endpoint failed"
        
        # Test bosses endpoint
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/bosses || echo "Bosses endpoint failed"
