name: Generate Item Database

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at midnight
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'webscraper/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r webscraper/requirements.txt

      - name: Generate valid item list
        working-directory: webscraper/runescape-items
        run: |
          python generate_valid_items.py

      - name: Run item scraper
        working-directory: webscraper/runescape-items
        env:
          # Optional: helps reduce 429s from wiki sources
          SCRAPER_USER_AGENT: "ScapeLabBot/1.0 (+github.com/QualitySushi/osrs-simulator)"
        run: |
          python osrs_item_scraper.py

      - name: Upload item database
        uses: actions/upload-artifact@v4
        with:
          name: osrs-item-database
          path: webscraper/runescape-items/*.db
          if-no-files-found: error
