name: Generate Item Database

on:
  schedule:
    - cron: '0 0 * * 0'  # Sundays 00:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCRAPER_USER_AGENT: "ScapeLabBot/1.0 (+github.com/QualitySushi/osrs-simulator)"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            tools/scraper_v2/requirements.txt
            tools/scrapers/requirements.txt
            backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tools/scraper_v2/requirements.txt ]; then
            pip install -r tools/scraper_v2/requirements.txt
          elif [ -f tools/scrapers/requirements.txt ]; then
            pip install -r tools/scrapers/requirements.txt
          else
            pip install -r backend/requirements.txt
          fi

      - name: Pre-step: generate valid item list (if script exists)
        run: |
          set -e
          if [ -f tools/scraper_v2/jobs/items_prepare.py ]; then
            python -m tools.scraper_v2.jobs.items_prepare
          elif [ -f tools/scraper_v2/generate_valid_items.py ]; then
            python tools/scraper_v2/generate_valid_items.py
          elif [ -f tools/scrapers/runescape-items/generate_valid_items.py ]; then
            (cd tools/scrapers/runescape-items && python generate_valid_items.py)
          else
            echo "No explicit 'generate valid items' step found; continuing." 
          fi

      - name: Run item scraper (auto-detect entrypoint)
        env:
          SCRAPER_USER_AGENT: ${{ env.SCRAPER_USER_AGENT }}
        run: |
          set -euo pipefail
          if [ -f tools/scraper_v2/jobs/items.py ]; then
            python -m tools.scraper_v2.jobs.items
          elif [ -f tools/scraper_v2/run_item_scrape.py ]; then
            python tools/scraper_v2/run_item_scrape.py
          elif [ -f tools/scrapers/runescape-items/osrs_item_scraper.py ]; then
            (cd tools/scrapers/runescape-items && python osrs_item_scraper.py)
          else
            echo "No item scraper entrypoint found. Expected one of:"
            echo "  tools/scraper_v2/jobs/items.py"
            echo "  tools/scraper_v2/run_item_scrape.py"
            echo "  tools/scrapers/runescape-items/osrs_item_scraper.py (legacy)"
            exit 1
          fi

      - name: Locate generated DB(s)
        id: locate
        run: |
          set -euo pipefail
          mapfile -t files < <(find tools -maxdepth 6 -type f \( -iname "*item*.db" -o -iname "*items*.db" -o -iname "*.db" \))
          if [ "${#files[@]}" -eq 0 ]; then
            echo "No item DB files found under tools/**. Did the scraper write output?" >&2
            exit 1
          fi
          {
            echo "DB_PATHS<<EOF"
            for f in "${files[@]}"; do echo "$f"; done
            echo "EOF"
          } >> "$GITHUB_ENV"

      - name: Upload item database
        uses: actions/upload-artifact@v4
        with:
          name: osrs-item-database
          path: ${{ env.DB_PATHS }}
          if-no-files-found: error
