name: Generate Item Database

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'backend/requirements.txt'

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Generate valid item list
        run: |
          cd backend/webscraper/runescape-items/
          python generate_valid_items.py

      - name: Run item scraper
        run: |
          cd backend/webscraper/runescape-items/
          python osrs_item_scraper.py

      - name: Upload item database
        uses: actions/upload-artifact@v4
        with:
          name: osrs-item-database
          path: backend/webscraper/runescape-items/*.db
