name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [stubbed, realdb]

    env:
      PYTHONUNBUFFERED: "1"
      SQLAZURECONNSTR_DefaultConnection: ${{ secrets.SQLAZURECONNSTR_DefaultConnection }}
      # Toggle stubs per matrix:
      OSRS_USE_STUBS: ${{ matrix.mode == 'realdb' && '0' || '1' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: backend/requirements.txt

      - name: Install ODBC Driver 18 (works on noble via jammy repo)
        if: matrix.mode == 'realdb'
        run: |
          set -e
          # Clean previous conflicting entries/keys
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list /etc/apt/sources.list.d/mssql-release.list
          sudo rm -f /etc/apt/trusted.gpg.d/microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.asc /etc/apt/keyrings/microsoft.gpg
          # Add keyring
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
          # Use jammy repo on noble runners
          echo "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" \
            | sudo tee /etc/apt/sources.list.d/microsoft-prod.list > /dev/null
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r backend/requirements.txt
          pip install pytest httpx python-dotenv

      - name: Show mode
        run: |
          echo "Mode: ${{ matrix.mode }}"
          echo "OSRS_USE_STUBS=${OSRS_USE_STUBS}"

      - name: Run tests
        run: |
          python backend/app/testing/UnitTest.py
